spring:
  application:
    name: hifive

  profiles:
    include: private
    active: dev # 기본 활성화 프로파일을 dev로 설정

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
  file:
    name: logs/spring-boot-application.log